server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
